version: '3.9'

networks:
  book-example:

services:
  sql:
    image: mariadb:10.5.9
    container_name: 'book-example-sql'
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: sql
      MYSQL_DATABASE: test
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=root
      interval: 5s
      retries: 5
    networks:
      - book-example
  graph:
    image: neo4j:5
    container_name: 'book-example-graph'
    restart: always
    ports:
      - '7687:7687'
      - '7474:7474'
    environment:
      NEO4J_AUTH: neo4j/test
      NEO4J_dbms_security_auth__minimum__password__length: 4
    healthcheck:
      test: "wget -q --method=HEAD http://localhost:7474 || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - book-example
  php:
    build:
      context: .
    container_name: 'book-example-php'
    networks:
      - book-example
    working_dir: /opt/project
    volumes:
      - ./:/opt/project
    depends_on:
      sql:
        condition: service_healthy
      graph:
        condition: service_healthy
    env_file:
      - .env